server:
  port: 8082

spring:
  application:
    name: order

eureka:
  client:
    # register-with-eureka: true
    # fetch-registry: true
    service-url:
      default-zone: http://seckill:P@ssw0rd@localhost:8761/eureka
